apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization



resources:
- ../common/cert-manager/cert-manager/base
- ../common/cert-manager/kubeflow-issuer/base
- ../common/istio-1-17/istio-crds/base
- ../common/istio-1-17/istio-namespace/base
- ../common/istio-1-17/istio-install/base

