apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx-helm-repo
  namespace: cluster-config
spec:
  interval: 5m0s
  url: https://kubernetes.github.io/ingress-nginx