apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: cluster-config
spec:
  targetNamespace: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: '4.5.2'
      sourceRef:
        kind: HelmRepository
        name: nginx-helm-repo
        namespace: cluster-config
  interval: 5m
  install:
    remediation:
      retries: 5
  upgrade:
    force: true
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: uninstall
  values:
    controller:
      service:
        external:
            enabled: true
        # internal:
        #     enabled: true
        #     externalTrafficPolicy: "Local"
        #     annotations:
        #       service.beta.kubernetes.io/azure-load-balancer-internal: "true"
        #       service.beta.kubernetes.io/azure-load-balancer-internal-subnet: ${INGRESS_SNET_NAME}
      metrics:
        enabled: false
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "10254"
      # podAnnotations:
      #   prometheus.io/scrape: "true"
      #   prometheus.io/port: "10254"
      #   traffic.sidecar.istio.io/excludeInboundPorts: "443"
      #   traffic.sidecar.istio.io/includeInboundPorts: ""
      #   sidecar.istio.io/proxyCPULimit: 1000m
      #   sidecar.istio.io/proxyMemoryLimit: 1024Mi
      replicaCount: 1
      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 5
        targetCPUUtilizationPercentage: 70
        targetMemoryUtilizationPercentage: 70
      resources:
        limits:
          cpu: 250m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 256Mi
      image:
        repository: registry.k8s.io/ingress-nginx/controller
        tag: v1.6.4
        digest: ""
      # extraVolumes:
      #   - name: secrets-store-inline
      #     csi:
      #       driver: secrets-store.csi.k8s.io
      #       readOnly: true
      #       volumeAttributes:
      #         secretProviderClass: "azure-tls"
      # extraVolumeMounts:
      #   - name: secrets-store-inline
      #     mountPath: "/mnt/secrets-store"
      #     readOnly: true

    defaultBackend:
      enabled: false
      image:
        repository: registry.k8s.io/defaultbackend-amd64
        tag: 1.5
        digest: ""