apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Kubeflow namespace
- ../manifests/common/kubeflow-namespace/base
# Kubeflow Roles
- ../manifests/common/kubeflow-roles/base
# Kubeflow Istio Resources
- ../manifests/common/istio-1-17/kubeflow-istio-resources/base

