apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

# Cert-Manager
- ../manifests/common/cert-manager/cert-manager/base
- ../manifests/common/cert-manager/kubeflow-issuer/base
# Istio
- ../manifests/common/istio-1-17/istio-crds/base
- ../manifests/common/istio-1-17/istio-namespace/base
- ../manifests/common/istio-1-17/istio-install/base
# OIDC Authservice
- ../manifests/common/oidc-client/oidc-authservice/base
# Dex
- ../manifests/common/dex/overlays/istio
# KNative
- ../manifests/common/knative/knative-serving/overlays/gateways
- ../manifests/common/knative/knative-eventing/base
- ../manifests/common/istio-1-17/cluster-local-gateway/base

